spring:
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML
      cache: false
   messages:
      basename: i18n/messages

   type: com.zaxxer.hikari.HikariDataSource
   hikari:
      min-idle: 10                          
      max-pool-size: 30                     
      idle-timeout: 600000                  
      max-lifetime: 1800000                 
      connection-timeout: 30000             
      connection-test-query: SELECT 1       
   sql:
      init: classpath:db/init.sql
   datasource:
      url: 'jdbc:sqlite::resource:db/sqlite.db'
      username:
      password:
      driver-class-name: org.sqlite.JDBC

   devtools:
      restart:
         enabled: true
         additional-paths: src/main/java
         additional-exclude: db/**, json/**, META-INF/additional-spring-configuration-metadata.json

knife4j:
  enable: true
  basic:
    enable: false
    username: 
    password: 
  production: false

notice:
  location: classpath:json/notice.json
  
api:
  rule-market: 'https://jproxy.lckp.top'
  
cron:
  add-count: '-'



