version: "3"
services:
  jproxy:
    image: manduted/jproxy:latest
    container_name: jproxy
    environment:
      - TZ=Asia/Shanghai
      - "JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - /docker/jproxy/config:/app/config
    network_mode: host
    restart: unless-stopped